# Generated by Django 4.2.5 on 2024-03-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="image/")),
                ("detail", models.CharField(max_length=100)),
                ("designation", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Beardstyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("beardstyle", models.CharField(max_length=20)),
                ("price", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="image/")),
                ("description", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("lastname", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.IntegerField()),
                ("purpose", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Hairstyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hairstyle", models.CharField(max_length=20)),
                ("price", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("lastname", models.CharField(max_length=20)),
                ("phone", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("barber1", models.CharField(max_length=20)),
                ("t_date", models.CharField(max_length=10)),
                ("t_time", models.CharField(max_length=10)),
                ("comment", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Massage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("massage", models.CharField(max_length=20)),
                ("price", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="image/")),
            ],
        ),
    ]
