# Generated by Django 4.2.5 on 2024-03-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Barber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uname", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Confirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("lastname", models.CharField(max_length=20)),
                ("phone", models.IntegerField()),
                ("barber1", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("t_date", models.CharField(max_length=10)),
                ("t_time", models.CharField(max_length=10)),
                ("comment", models.CharField(max_length=50)),
            ],
        ),
    ]
